# Generated by Django 3.0.8 on 2020-07-27 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='emp_pos',
        ),
        migrations.DeleteModel(
            name='Postion',
        ),
    ]
