# Generated by Django 3.0.8 on 2020-07-27 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0002_auto_20200727_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='emp_Email',
            field=models.CharField(default=0, max_length=30),
            preserve_default=False,
        ),
    ]
